import type { Metadata } from "next";
import { Section } from "@/components/Section";

export const metadata: Metadata = { title: "Privacy Policy | Mind.AI" };

/**
 * Privacy policy. Confirm the canonical copy with legal before launch.
 */
export default function Page() {
  return (
    <Section>
      <article className="prose-mindai mx-auto max-w-3xl">
        <h1 className="h-display text-4xl">Privacy Policy</h1>
        <p className="mt-2 text-sm text-gray-500">
          Last updated: October 06, 2024
        </p>

        <p className="mt-6 text-gray-600">
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
        </p>
        <p className="mt-4 text-gray-600">
          We use Your Personal data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy.
        </p>

        <Heading>Interpretation and Definitions</Heading>
        <SubHeading>Interpretation</SubHeading>
        <p className="text-gray-600">
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions shall
          have the same meaning regardless of whether they appear in singular or
          plural.
        </p>

        <SubHeading>Definitions</SubHeading>
        <p className="text-gray-600">For the purposes of this Privacy Policy:</p>
        <ul className="ml-5 list-disc space-y-2 text-gray-600">
          <li>
            <strong>Account</strong> means a unique account created for You to
            access our Service or parts of our Service.
          </li>
          <li>
            <strong>Company</strong> (referred to as either &quot;the
            Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in
            this Agreement) refers to Mind.AI.
          </li>
          <li>
            <strong>Cookies</strong> are small files that are placed on Your
            computer, mobile device or any other device by a website.
          </li>
          <li>
            <strong>Country</strong> refers to: Karnataka, India
          </li>
          <li>
            <strong>Device</strong> means any device that can access the Service
            such as a computer, a cellphone or a digital tablet.
          </li>
          <li>
            <strong>Personal Data</strong> is any information that relates to an
            identified or identifiable individual.
          </li>
          <li>
            <strong>Service</strong> refers to the Website.
          </li>
          <li>
            <strong>Service Provider</strong> means any natural or legal person
            who processes the data on behalf of the Company.
          </li>
          <li>
            <strong>Usage Data</strong> refers to data collected automatically,
            either generated by the use of the Service or from the Service
            infrastructure itself.
          </li>
          <li>
            <strong>Website</strong> refers to Mind.AI, accessible from
            https://www.mind.ai/
          </li>
          <li>
            <strong>You</strong> means the individual accessing or using the
            Service, or the company, or other legal entity on behalf of which
            such individual is accessing or using the Service.
          </li>
        </ul>

        <Heading>Collecting and Using Your Personal Data</Heading>
        <SubHeading>Types of Data Collected</SubHeading>
        <p className="text-gray-600">
          <strong>Personal Data.</strong> While using Our Service, We may ask You
          to provide Us with certain personally identifiable information,
          including but not limited to: email address, first name and last name,
          phone number, and Usage Data.
        </p>
        <p className="mt-4 text-gray-600">
          <strong>Usage Data</strong> is collected automatically when using the
          Service and may include information such as Your Device&apos;s IP
          address, browser type and version, the pages of our Service that You
          visit, the time and date of Your visit, the time spent on those pages,
          unique device identifiers and other diagnostic data.
        </p>

        <SubHeading>Tracking Technologies and Cookies</SubHeading>
        <p className="text-gray-600">
          We use Cookies and similar tracking technologies to track the activity
          on Our Service and store certain information. We use both Session and
          Persistent Cookies for necessary/essential purposes, notice acceptance,
          and functionality.
        </p>

        <SubHeading>Use of Your Personal Data</SubHeading>
        <p className="text-gray-600">
          The Company may use Personal Data to provide and maintain our Service,
          manage Your Account, perform contracts, contact You, provide You with
          news and offers, manage Your requests, complete business transfers, and
          for data analysis and Service improvement.
        </p>

        <Heading>Retention, Transfer and Deletion</Heading>
        <p className="text-gray-600">
          The Company will retain Your Personal Data only for as long as is
          necessary for the purposes set out in this Privacy Policy. Your
          information may be transferred to — and maintained on — computers
          located outside of Your jurisdiction. You have the right to delete or
          request that We assist in deleting the Personal Data We have collected
          about You.
        </p>

        <Heading>Children&apos;s Privacy</Heading>
        <p className="text-gray-600">
          Our Service does not address anyone under the age of 13. We do not
          knowingly collect personally identifiable information from anyone under
          the age of 13.
        </p>

        <Heading>Changes to this Privacy Policy</Heading>
        <p className="text-gray-600">
          We may update Our Privacy Policy from time to time. We will notify You
          of any changes by posting the new Privacy Policy on this page and
          updating the &quot;Last updated&quot; date.
        </p>

        <Heading>Contact Us</Heading>
        <p className="text-gray-600">
          If you have any questions about this Privacy Policy, You can contact us
          at{" "}
          <a href="mailto:privacy@mind.ai" className="text-brand">
            privacy@mind.ai
          </a>
          .
        </p>
      </article>
    </Section>
  );
}

function Heading({ children }: { children: React.ReactNode }) {
  return (
    <h2 className="mt-10 font-display text-2xl font-semibold text-gray-900">
      {children}
    </h2>
  );
}
function SubHeading({ children }: { children: React.ReactNode }) {
  return (
    <h3 className="mb-2 mt-6 font-display text-lg font-semibold text-gray-800">
      {children}
    </h3>
  );
}
