"""screening sessions and scores

Revision ID: a014c69d0cb7
Revises: 0001
Create Date: 2026-09-04 14:09:43.566757
"""
from alembic import op
import sqlalchemy as sa


revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screening_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('instrument', sa.String(length=20), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('instrument_validated', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_screening_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_screening_sessions'))
    )
    op.create_index(op.f('ix_screening_sessions_user_id'), 'screening_sessions', ['user_id'], unique=False)
    op.create_table('screening_scores',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('subscale', sa.String(length=20), nullable=False),
    sa.Column('raw', sa.Integer(), nullable=False),
    sa.Column('severity_band', sa.String(length=20), nullable=False),
    sa.Column('items_answered', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['screening_sessions.id'], name=op.f('fk_screening_scores_session_id_screening_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_screening_scores'))
    )
    op.create_index(op.f('ix_screening_scores_session_id'), 'screening_scores', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screening_scores_session_id'), table_name='screening_scores')
    op.drop_table('screening_scores')
    op.drop_index(op.f('ix_screening_sessions_user_id'), table_name='screening_sessions')
    op.drop_table('screening_sessions')
    # ### end Alembic commands ###
