"""checkins and signals

Revision ID: 9aa30c8b322e
Revises: 0002
Create Date: 2026-09-04 16:44:17.928036
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkins',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mood', sa.SmallInteger(), nullable=False),
    sa.Column('sleep_hours', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('energy', sa.SmallInteger(), nullable=True),
    sa.Column('social', sa.SmallInteger(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('ack_key', sa.String(length=60), nullable=False),
    sa.Column('suggestion_title_key', sa.String(length=60), nullable=True),
    sa.Column('suggestion_body_key', sa.String(length=60), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_checkins_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checkins')),
    sa.UniqueConstraint('user_id', 'local_date', name='uq_checkins_user_id')
    )
    op.create_index(op.f('ix_checkins_user_id'), 'checkins', ['user_id'], unique=False)
    op.create_table('signals',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_signals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals'))
    )
    op.create_index(op.f('ix_signals_source_id'), 'signals', ['source_id'], unique=False)
    op.create_index(op.f('ix_signals_user_id'), 'signals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_user_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_source_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_checkins_user_id'), table_name='checkins')
    op.drop_table('checkins')
    # ### end Alembic commands ###
