"""checkin appetite and activity

Revision ID: 8805503577dd
Revises: 0005
Create Date: 2026-09-04 21:29:03.954001
"""
from alembic import op
import sqlalchemy as sa


revision = "0006"
down_revision = "0005"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkins', sa.Column('appetite', sa.SmallInteger(), nullable=True))
    op.add_column('checkins', sa.Column('activity', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checkins', 'activity')
    op.drop_column('checkins', 'appetite')
    # ### end Alembic commands ###
